# Generated by Django 3.1.3 on 2020-12-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cst', '0002_people_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='peo_to_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_date', models.DateField()),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cst.people')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cst.tag')),
            ],
            options={
                'unique_together': {('p', 't')},
            },
        ),
    ]
